apiVersion: v1
kind: Service
metadata:
  name: fetch-block-service
spec:
  ports:
    - targetPort: 8787
      nodePort: 30087
      port: 80
  selector:
    app: fetch-blocks
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocks-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-blocks
  template:
    metadata:
      labels:
        app: fetch-blocks
    spec:
      containers:
      - name: find-blocks
        image: dockersourabh123/fetch_blocks:1.1.3
        ports:
        - containerPort: 8787


